name = "teacher-salary-tracker"
main = "src/worker/index.ts"
compatibility_date = "2026-05-10"

[triggers]
crons = ["0 3 * * *"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "teacher_salary_tracker"
database_id = "138a4c6a-0d05-47b1-a89c-965e03de560b"
